### PR TITLE
Added support for logging Scopes

### PR DESCRIPTION
**Pull request by webseb**
Hi Rory,

your tool has been most helpful over the last months. Thank you for the time you put into it!

I just wanted to be able to see logging scopes (i.e. BeginScope<TState>) in my test output as well.

This is my first ever pull request so I hope I did this the right way.

Best regards,

Sebastian

### CODE REVIEW

**Comment by roryprimrose** [comment]
Thanks Sebastian. This looks good. I'm going to spend a bit of time to review it.

**Comment by roryprimrose** [comment]
I've had a play with the code you have put together. I like the outcome but want to see a cleaner relationship between TestOutputLogger, scope tracking and CacheLogger. I'm trying to come up with a cleaner way of using the disposal of scopes to clean up the tracking of scopes.

I've also be thinking about how the scopes are written to the output. I would prefer the scope to write their scope value at the beginning and end of the scope but only write the latest scope value rather than the complete collection of scopes. I'm also thinking about using simple nested whitespace in the output to visually identify the relationship/stack of scopes among the log outputs. Would this still suit your purpose?

I'll play with these ideas over the next few days and push a branch with what I'm thinking.

**Comment by webseb** [comment]
I was (somewhat) following [Nicholas Blumhardt's post](https://nblumhardt.com/2016/11/ilogger-beginscope/) about how they do it in Serilog but as long as the scopes show up somewhere it'll work for me.

**Comment by roryprimrose** [comment]
First change is done. I renamed Scope to CacheScope because it is really just a wrapper around the scope from the ILogger in CacheLogger. CacheLogger itself is just a wrapper. The naming of the Scope class caused a little confusion. I also passed an Action to it so that the CacheScope was not directly coupled to the private _scopes field of CacheLogger.

There was also a potential bug where the innerScope would be null if the _logger.BeginScope returned null. This would have caused a NullReferenceException when the CacheLogger.Scope instance was disposed. Changing that code from 
```_logger != null ? _logger.BeginScope(state) : NoopDisposable.Instance;``` 
to 
```_logger?.BeginScope(state) ?? NoopDisposable.Instance;``` 
covers both the scenarios where _logger is null or the scope returned from its BeginScope is null.

**Comment by roryprimrose** [comment]
I think I'm quite happy with this. A good example of the changes I've made to your excellent pull request is in the following test.

```
        [Fact]
        public void LogEntryContainsSnapshotOfActiveScopes()
        {
            var logger = _output.BuildLogger();

            logger.LogCritical("Writing critical message");
            logger.LogDebug("Writing debug message");
            logger.LogError("Writing error message");
            logger.LogInformation("Writing information message");
            logger.LogTrace("Writing trace message");
            logger.LogWarning("Writing warning message");

            using (logger.BeginScope("First scope"))
            {
                logger.LogInformation("Inside first scope");

                using (logger.BeginScope("Second scope"))
                {
                    logger.LogInformation("Inside second scope");
                }

                logger.LogInformation("After second scope");
            }

            logger.LogInformation("After first scope");
        }
```
This results in the following being written to the xunit test output.
```

Critical [0]: Writing critical message
Debug [0]: Writing debug message
Error [0]: Writing error message
Information [0]: Writing information message
Trace [0]: Writing trace message
Warning [0]: Writing warning message
<First scope>
   Information [0]: Inside first scope
   <Second scope>
      Information [0]: Inside second scope
   </Second scope>
   Information [0]: After second scope
</First scope>
Information [0]: After first scope
```

Does this still satisfy what you were trying to achieve?

**Comment by webseb** [comment]
It gives a nice structured view of the log entries including indentation of messages inside the scope. I like it.

**Comment by roryprimrose** [comment]
@webseb Thank you for the pull request. I have pushed 2.0.0 with your logging scopes onto nuget.org.

**Comment by roryprimrose** [comment]
FYI - https://www.neovolve.com/2019/03/25/supporting-scopes-with-xunit-ilogger/

**Pull request merged**
